/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.clinica.view;

import java.net.URL;
import com.clinica.*;

/**
 *
 * @author Jonathan
 */
public class GerenteUI extends javax.swing.JFrame {

    /**
     * Creates new form GerenteUI
     */
    
    private LoginUI l;
   
    URL url  = this.getClass().getResource("/com/clinica/images/gerente.png");
    
    public GerenteUI() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setIconImage(this.getToolkit().getImage(url));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastrosMenu = new javax.swing.JMenu();
        addpacienteMenu = new javax.swing.JMenuItem();
        addmedicoMenu = new javax.swing.JMenuItem();
        addatendenteMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        addsalarioMenu = new javax.swing.JMenuItem();
        addvalorCMenu = new javax.swing.JMenuItem();
        consultasMenu = new javax.swing.JMenu();
        cpacienteMenu = new javax.swing.JMenuItem();
        cmedicoMenu = new javax.swing.JMenuItem();
        catendenteMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        cfolhapagamentoMenu = new javax.swing.JMenuItem();
        chistoricofrequenciaMenu = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        clistapacienteMenu = new javax.swing.JMenuItem();
        clistamedicoMenu = new javax.swing.JMenuItem();
        clistaatendenteMenu = new javax.swing.JMenuItem();
        sairMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerente");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName("gerenteFrame"); // NOI18N
        setUndecorated(true);
        setSize(new java.awt.Dimension(2147483647, 2147483647));

        backgroundPanel.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        cadastrosMenu.setBackground(new java.awt.Color(255, 255, 255));
        cadastrosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/cadastro.png"))); // NOI18N
        cadastrosMenu.setText("Cadastros");
        cadastrosMenu.setBorderPainted(false);
        cadastrosMenu.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N

        addpacienteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        addpacienteMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addpacienteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/pessoa.png"))); // NOI18N
        addpacienteMenu.setText("Cadastrar Paciente");
        cadastrosMenu.add(addpacienteMenu);

        addmedicoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        addmedicoMenu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addmedicoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/medico.png"))); // NOI18N
        addmedicoMenu.setText("Cadastrar Médico");
        cadastrosMenu.add(addmedicoMenu);

        addatendenteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        addatendenteMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addatendenteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/atendente.png"))); // NOI18N
        addatendenteMenu.setText("Cadastrar Atendente");
        cadastrosMenu.add(addatendenteMenu);
        cadastrosMenu.add(jSeparator1);

        addsalarioMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        addsalarioMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addsalarioMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/Salario.png"))); // NOI18N
        addsalarioMenu.setText("Cadastrar Salário");
        cadastrosMenu.add(addsalarioMenu);

        addvalorCMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        addvalorCMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addvalorCMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/valorConsulta.png"))); // NOI18N
        addvalorCMenu.setText("Cadastrar Valor De Consulta");
        cadastrosMenu.add(addvalorCMenu);

        jMenuBar1.add(cadastrosMenu);

        consultasMenu.setBackground(new java.awt.Color(255, 255, 255));
        consultasMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/search.png"))); // NOI18N
        consultasMenu.setText("Consultas");
        consultasMenu.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N

        cpacienteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        cpacienteMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cpacienteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/pessoa.png"))); // NOI18N
        cpacienteMenu.setText("Paciente");
        consultasMenu.add(cpacienteMenu);

        cmedicoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        cmedicoMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmedicoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/medico.png"))); // NOI18N
        cmedicoMenu.setText("Médico");
        consultasMenu.add(cmedicoMenu);

        catendenteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        catendenteMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        catendenteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/atendente.png"))); // NOI18N
        catendenteMenu.setText("Atendente");
        consultasMenu.add(catendenteMenu);
        consultasMenu.add(jSeparator2);

        cfolhapagamentoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        cfolhapagamentoMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cfolhapagamentoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/folhaPagamento.png"))); // NOI18N
        cfolhapagamentoMenu.setText("Folha De Pagamento");
        consultasMenu.add(cfolhapagamentoMenu);

        chistoricofrequenciaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        chistoricofrequenciaMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chistoricofrequenciaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/frequencia.png"))); // NOI18N
        chistoricofrequenciaMenu.setText("Histórico De Frequência");
        consultasMenu.add(chistoricofrequenciaMenu);
        consultasMenu.add(jSeparator3);

        clistapacienteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        clistapacienteMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        clistapacienteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/pessoa.png"))); // NOI18N
        clistapacienteMenu.setText("Lista De Pacientes");
        consultasMenu.add(clistapacienteMenu);

        clistamedicoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        clistamedicoMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        clistamedicoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/medico.png"))); // NOI18N
        clistamedicoMenu.setText("Lista De Médicos");
        consultasMenu.add(clistamedicoMenu);

        clistaatendenteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        clistaatendenteMenu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        clistaatendenteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/atendente.png"))); // NOI18N
        clistaatendenteMenu.setText("Lista De Atendentes");
        consultasMenu.add(clistaatendenteMenu);

        jMenuBar1.add(consultasMenu);

        sairMenu.setBackground(new java.awt.Color(255, 255, 255));
        sairMenu.setForeground(new java.awt.Color(255, 51, 51));
        sairMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/clinica/images/signout.png"))); // NOI18N
        sairMenu.setText("Sair");
        sairMenu.setToolTipText("");
        sairMenu.setFocusPainted(true);
        sairMenu.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        sairMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairMenuMouseEntered(evt);
            }
        });
        jMenuBar1.add(sairMenu);
        sairMenu.getAccessibleContext().setAccessibleName("Sair");

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sairMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMenuMouseClicked
        
       l = new LoginUI();
       
       l.setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_sairMenuMouseClicked

    private void sairMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMenuMouseEntered
        sairMenu.setToolTipText("Aperte para sair");
    }//GEN-LAST:event_sairMenuMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenteUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addatendenteMenu;
    private javax.swing.JMenuItem addmedicoMenu;
    private javax.swing.JMenuItem addpacienteMenu;
    private javax.swing.JMenuItem addsalarioMenu;
    private javax.swing.JMenuItem addvalorCMenu;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JMenu cadastrosMenu;
    private javax.swing.JMenuItem catendenteMenu;
    private javax.swing.JMenuItem cfolhapagamentoMenu;
    private javax.swing.JMenuItem chistoricofrequenciaMenu;
    private javax.swing.JMenuItem clistaatendenteMenu;
    private javax.swing.JMenuItem clistamedicoMenu;
    private javax.swing.JMenuItem clistapacienteMenu;
    private javax.swing.JMenuItem cmedicoMenu;
    private javax.swing.JMenu consultasMenu;
    private javax.swing.JMenuItem cpacienteMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu sairMenu;
    // End of variables declaration//GEN-END:variables
}
